import {Heading, Theme} from "@radix-ui/themes";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/app/globals.css";
import '@radix-ui/themes/styles.css';
import {Toaster} from "react-hot-toast";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "CryptoPay Server",
  // description: "Generated by create next app",
};

export default async function RootLayout({
 children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Theme accentColor="blue">
      <Toaster />
      <div className="min-w-screen min-h-screen md:bg-gray-100">
        <div className="text-center pt-8 md:pb-4 md:px-8">
          <Heading size="6">CryptoPay Server</Heading>
          <div className="bg-white md:rounded-lg md:shadow-md p-4 max-w-sm mx-auto mt-4">
            {children}
          </div>
        </div>
        <div className="text-center pb-4 text-gray-400">
          Contact: dawid.paszko@gmail.com
        </div>
      </div>
    </Theme>
    </body>
    </html>
  );
}
